image: docker:stable
stages:
  - test
  - build
  - deploy

services:
  - docker:dind

test:
  stage: test
  script:
    - python backend/manage.py test

build:
  only:
    refs:
      - master
  stage: build
  script:
    - docker info
    - echo "registering with $REGISTRY_USERNAME $REGISTRY_PASSWORD"
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USERNAME --password-stdin registry.gitlab.com
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  only:
    - tags
  stage: deploy
  script:
    - apk add --update curl wget
    - wget https://git.dadard.fr/dadard/scripts/raw/branch/master/deploy.sh
    - export CONTAINER_NAME
    - export IMAGE_NAME
    - export POD_NAME
    - export DEPLOYER_URL
    - export DEPLOYER_TOKEN
    - echo "deploying container $CONTAINER_NAME ($IMAGE_NAME) with API $DEPLOYER_URL in pod $POD_NAME"
    - sh deploy.sh

